apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-date
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task
            image: registry.access.redhat.com/ubi9/ubi
            command: ["bash", "-c", "echo $(date) - Task executed"]
          restartPolicy: OnFailure

